import { Category, Product } from "@/types/product";

export const MOCK_CATEGORIES: (Category & { emoji: string; gradient: string; textColor: string })[] = [
  {
    id: "cat-1",
    name: "Rau củ",
    slug: "rau-cu",
    description: "Rau xanh, củ quả tươi sạch mỗi ngày",
    image: null,
    parentId: null,
    sortOrder: 1,
    isActive: true,
    emoji: "🥦",
    gradient: "from-green-50 to-emerald-100",
    textColor: "text-green-700",
    _count: { products: 45 },
  },
  {
    id: "cat-2",
    name: "Thịt heo",
    slug: "thit-heo",
    description: "Thịt heo tươi, từ trang trại sạch",
    image: null,
    parentId: null,
    sortOrder: 2,
    isActive: true,
    emoji: "🥩",
    gradient: "from-red-50 to-rose-100",
    textColor: "text-red-700",
    _count: { products: 20 },
  },
  {
    id: "cat-3",
    name: "Thịt bò",
    slug: "thit-bo",
    description: "Thịt bò Úc, Mỹ nhập khẩu cao cấp",
    image: null,
    parentId: null,
    sortOrder: 3,
    isActive: true,
    emoji: "🫀",
    gradient: "from-orange-50 to-amber-100",
    textColor: "text-orange-700",
    _count: { products: 15 },
  },
  {
    id: "cat-4",
    name: "Hải sản",
    slug: "hai-san",
    description: "Tôm, cá, mực tươi từ biển mỗi ngày",
    image: null,
    parentId: null,
    sortOrder: 4,
    isActive: true,
    emoji: "🦐",
    gradient: "from-blue-50 to-cyan-100",
    textColor: "text-blue-700",
    _count: { products: 30 },
  },
  {
    id: "cat-5",
    name: "Thịt gà",
    slug: "thit-ga",
    description: "Gà ta, gà công nghiệp tươi sạch",
    image: null,
    parentId: null,
    sortOrder: 5,
    isActive: true,
    emoji: "🍗",
    gradient: "from-yellow-50 to-amber-100",
    textColor: "text-yellow-700",
    _count: { products: 18 },
  },
  {
    id: "cat-6",
    name: "Đồ chế biến",
    slug: "do-che-bien",
    description: "Thực phẩm đông lạnh, chế biến sẵn",
    image: null,
    parentId: null,
    sortOrder: 6,
    isActive: true,
    emoji: "🥗",
    gradient: "from-purple-50 to-violet-100",
    textColor: "text-purple-700",
    _count: { products: 25 },
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p-1",
    name: "Cải bó xôi hữu cơ Đà Lạt",
    slug: "cai-bo-xoi-huu-co-da-lat",
    description: "Cải bó xôi (spinach) trồng theo tiêu chuẩn hữu cơ tại Đà Lạt, giàu dinh dưỡng.",
    shortDescription: "Cải bó xôi hữu cơ, không thuốc trừ sâu",
    price: 35000,
    salePrice: 28000,
    sku: "VEG-001",
    stock: 120,
    unit: "bó",
    weight: 300,
    origin: "Đà Lạt, Lâm Đồng",
    status: "ACTIVE",
    isFeatured: true,
    isOrganic: true,
    isCore: false,
    categoryId: "cat-1",
    soldCount: 234,
    viewCount: 1200,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.8,
    reviewCount: 56,
    images: [
      {
        id: "img-1",
        url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop&q=80",
        alt: "Cải bó xôi hữu cơ",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
  {
    id: "p-2",
    name: "Thăn nội bò Úc nhập khẩu",
    slug: "than-noi-bo-uc-nhap-khau",
    description: "Thăn nội bò Úc chính hãng, mềm ngọt, phù hợp nướng và xào.",
    shortDescription: "Thăn nội bò Úc, nhập khẩu chính hãng",
    price: 320000,
    salePrice: 285000,
    sku: "BEEF-001",
    stock: 45,
    unit: "500g",
    weight: 500,
    origin: "Úc",
    status: "ACTIVE",
    isFeatured: true,
    isOrganic: false,
    isCore: false,
    categoryId:"cat-3",
    soldCount: 189,
    viewCount: 980,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.9,
    reviewCount: 42,
    images: [
      {
        id: "img-2",
        url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=400&fit=crop&q=80",
        alt: "Thăn nội bò Úc",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
  {
    id: "p-3",
    name: "Tôm sú tươi sống loại 1",
    slug: "tom-su-tuoi-song-loai-1",
    description: "Tôm sú tươi sống, đánh bắt tự nhiên, kích cỡ đều, thịt chắc ngọt.",
    shortDescription: "Tôm sú tươi sống, kích cỡ 30-40 con/kg",
    price: 280000,
    salePrice: null,
    sku: "SEA-001",
    stock: 60,
    unit: "kg",
    weight: 1000,
    origin: "Cà Mau",
    status: "ACTIVE",
    isFeatured: true,
    isOrganic: false,
    isCore: false,
    categoryId:"cat-4",
    soldCount: 310,
    viewCount: 1560,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.7,
    reviewCount: 78,
    images: [
      {
        id: "img-3",
        url: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=400&fit=crop&q=80",
        alt: "Tôm sú tươi",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
  {
    id: "p-4",
    name: "Gà ta thả vườn nguyên con",
    slug: "ga-ta-tha-vuon-nguyen-con",
    description: "Gà ta thả vườn, nuôi tự nhiên không kháng sinh, thịt chắc, ngọt đậm.",
    shortDescription: "Gà ta thả vườn, khoảng 1.2–1.5 kg/con",
    price: 165000,
    salePrice: 148000,
    sku: "CHK-001",
    stock: 35,
    unit: "con",
    weight: 1300,
    origin: "Long An",
    status: "ACTIVE",
    isFeatured: true,
    isOrganic: false,
    isCore: false,
    categoryId:"cat-5",
    soldCount: 156,
    viewCount: 820,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.6,
    reviewCount: 34,
    images: [
      {
        id: "img-4",
        url: "https://images.unsplash.com/photo-1548550797-2f6e0a7e3bdd?w=400&h=400&fit=crop&q=80",
        alt: "Gà ta thả vườn",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
  {
    id: "p-5",
    name: "Cà chua bi cherry hữu cơ",
    slug: "ca-chua-bi-cherry-huu-co",
    description: "Cà chua bi cherry nhỏ, ngọt, trồng hữu cơ, giàu lycopene và vitamin C.",
    shortDescription: "Cà chua cherry hữu cơ, hộp 300g",
    price: 45000,
    salePrice: 38000,
    sku: "VEG-002",
    stock: 200,
    unit: "hộp",
    weight: 300,
    origin: "Đà Lạt, Lâm Đồng",
    status: "ACTIVE",
    isFeatured: true,
    isOrganic: true,
    isCore: false,
    categoryId: "cat-1",
    soldCount: 420,
    viewCount: 2100,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.9,
    reviewCount: 95,
    images: [
      {
        id: "img-5",
        url: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=400&fit=crop&q=80",
        alt: "Cà chua cherry hữu cơ",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
  {
    id: "p-6",
    name: "Ba chỉ heo tươi sạch",
    slug: "ba-chi-heo-tuoi-sach",
    description: "Ba chỉ heo từ heo sạch nuôi không tăng trọng, thịt tươi, phù hợp kho, luộc, nướng.",
    shortDescription: "Ba chỉ heo sạch, 500g",
    price: 95000,
    salePrice: null,
    sku: "PORK-001",
    stock: 80,
    unit: "500g",
    weight: 500,
    origin: "Bình Dương",
    status: "ACTIVE",
    isFeatured: true,
    isOrganic: false,
    isCore: false,
    categoryId:"cat-2",
    soldCount: 267,
    viewCount: 1340,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.5,
    reviewCount: 61,
    images: [
      {
        id: "img-6",
        url: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=400&fit=crop&q=80",
        alt: "Ba chỉ heo tươi",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
  {
    id: "p-7",
    name: "Cá hồi phi lê Na Uy tươi",
    slug: "ca-hoi-phi-le-na-uy-tuoi",
    description: "Cá hồi phi lê Na Uy nhập khẩu, thịt đỏ tươi, giàu Omega-3, phù hợp làm sushi, áp chảo.",
    shortDescription: "Cá hồi phi lê Na Uy, 300g/miếng",
    price: 185000,
    salePrice: 165000,
    sku: "SEA-002",
    stock: 55,
    unit: "300g",
    weight: 300,
    origin: "Na Uy",
    status: "ACTIVE",
    isFeatured: true,
    isOrganic: false,
    isCore: false,
    categoryId:"cat-4",
    soldCount: 198,
    viewCount: 1120,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.8,
    reviewCount: 47,
    images: [
      {
        id: "img-7",
        url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=400&fit=crop&q=80",
        alt: "Cá hồi phi lê Na Uy",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
  {
    id: "p-8",
    name: "Bắp cải tím hữu cơ",
    slug: "bap-cai-tim-huu-co",
    description: "Bắp cải tím giàu anthocyanin, chống oxy hóa, trồng sạch không hóa chất.",
    shortDescription: "Bắp cải tím hữu cơ, khoảng 600–800g/cây",
    price: 28000,
    salePrice: null,
    sku: "VEG-003",
    stock: 150,
    unit: "cây",
    weight: 700,
    origin: "Đà Lạt, Lâm Đồng",
    status: "ACTIVE",
    isFeatured: false,
    isOrganic: true,
    isCore: false,
    categoryId: "cat-1",
    soldCount: 312,
    viewCount: 890,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    averageRating: 4.4,
    reviewCount: 29,
    images: [
      {
        id: "img-8",
        url: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&h=400&fit=crop&q=80",
        alt: "Bắp cải tím hữu cơ",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
  },
];

export const HERO_STATS = [
  { value: "500+", label: "Sản phẩm" },
  { value: "10K+", label: "Khách hàng" },
  { value: "2-3h", label: "Giao hàng" },
  { value: "100%", label: "Tươi sạch" },
];
